### ISSUE TITLE
Runtime error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by twelve-monkeys** [auth0-blog/nest-react-blog-ga#13]
after fixing the lack of import to make it compile, I get...

`Compiled successfully!

You can now view blog-frontend in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.3:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\src\underbelly\frontend\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\src\underbelly\frontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:317:13)
    at C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\src\underbelly\frontend\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\src\underbelly\frontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:317:13)
    at C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\src\underbelly\frontend\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\src\underbelly\frontend\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\src\underbelly\frontend\node_modules\express\lib\router\layer.js:95:5)`

**Comment by michaelfouad** [comment]
upgrade your package.json from "react-scripts": "3.3.0" ->  "react-scripts": "3.4.1"
